### ISSUE TITLE
Update top-level CMakeLists.txt

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerTrackingErrorInspector#1]
set(EXTENSION_ICONURL "http://www.example.com/Slicer/Extensions/TrackingErrorInspector.png")
set(EXTENSION_SCREENSHOTURLS "http://www.example.com/Slicer/Extensions/TrackingErrorInspector/Screenshots/1.png")

**Comment by vinyasHarish95** [comment]
I am also changing the module icons and was wondering where to acknowledge the creator of a map vector. Is it just done as a comment in the CMakeLists for that module (Tracking Error Mapping)?

**Comment by lassoan** [comment]
Use icons that don't require attribution (add a comment in the CMakeLists.txt about the source of the image and its license).
https://pixabay.com/en/map-pin-icon-map-pin-travel-1272165/
