### ISSUE TITLE
Update acknowledgementText, authors, etc. in all py files.

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerTrackingErrorInspector#2]

**Comment by vinyasHarish95** [comment]
Updated the acknowledgement text in Tracking Error Mapping and Dual Modality Calibration to: ""This work was was funded by Cancer Care Ontario, the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO) and the Summer Work Experience Program (SWEP) at Queen's Unversity.""

Updated the acknowledgement text in Compare Displacement Fields to: "This work was was funded by Cancer Care Ontario and the Ontario Consortium for Adaptive Interventions in Radiation Oncology (OCAIRO)."

**Comment by vinyasHarish95** [comment]
Added Aidan as an contributor in the mapping and calibration modules as well as acknowledged his funding source.
