### ISSUE TITLE
Create icons for extension and each module

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerTrackingErrorInspector#6]
Extension icon:
https://github.com/SlicerIGT/SlicerIGT/blob/master/SlicerIGTLogoDesign.xcf
https://www.assembla.com/spaces/slicerrt/subversion/source/HEAD/trunk/MatlabBridge/doc/logo

Module icons:
http://www.rw-designer.com/3D_icon_editor.php

**Comment by vinyasHarish95** [comment]
Icons for extension and each module created
