### ISSUE TITLE
Add pivot calibration and landmark registration step to the dual modality calibration module

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerTrackingErrorInspector#9]
Pivot calibration:

It would determine EmPointerTipToEmPointer and OpPointerTipToOpPointer transforms.
Using these, landmark calibration could be done automatically, from randomly selected points.

See how it is done in LumpNav:
https://github.com/SlicerIGT/LumpNav/blob/master/LumpNav/LumpNav.py

Landmark registration:

Collect points automatically (when the tip moves less than 2mm for 2 seconds) or when a button is clicked. Stop when 8 points are collected.

**Comment by lassoan** [comment]
It's also an option to just pivot around 3-4 different points on the phantom. Then there would be no need for separate pivot calibration and then landmark registration.

**Comment by vinyasHarish95** [comment]
We determined that this is not necessary, just have clear instructions on the tutorial that we will be using other modules

**Comment by vinyasHarish95** [comment]
Added instructions to the private Assembla page, will make sure to include these instructions in the 3D Slicer Wiki page.
